### ISSUE TITLE
If env variables type validation fails, mlp error is not understandable

### ISSUE THREAD

**Issue by davidebianchi** [mia-platform/mlp#27]
**Describe the bug**
When deploy a Deployment resource with env var not set to string, the error is not clear: `unrecognized type: string`

**Expected behavior**
I expect a more clear error on how to fix the resource, or at least the kind and name or the file path of the resource which has the problem.

**To Reproduce**

Try to deply a resource like:

```yml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-case
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  schedule: '*/5 * * * *'
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          name: test-case
        spec:
          containers:
            - name: test-case
              image: busybox
              env:
                - name: SOME_ENV
                  value: 50
          restartPolicy: Never
```
