### ISSUE TITLE
[Docs]: generate Command - Unclear how to set the "file" value for secrets from file

### ISSUE THREAD

**Issue by silversoul93** [mia-platform/mlp#84]
### Documentation Revision

Hi guys,
I read on [this page](https://github.com/mia-platform/mlp/blob/main/docs/40_generate.md) I can read the secret content from literal or **from file**.
Regarding the **from file** case, I am not sure about what value should I use for the `file` property.

Are the following examples right?
```
secrets:
  - name: "my-secret-value-from-local-file"
    when: "always"
    data:
      - from: "file"
        file: ./path-to-file-in-same-repository

  - name: "my-secret-value-from-file-on-git-provider"
    when: "always"
    data:
      - from: "file"
        file: /path/to/same/git/provider/repository/file
```

Is there any other use case I am missing?

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct
