### ISSUE TITLE
[Bug]: Resources deleted in target namespace if malformed yaml file is provided

### ISSUE THREAD

**Issue by peppemanzi** [mia-platform/mlp#96]
### What version or versions you have tested?

v1.2.3

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### What did you expect to happen?

Malformed YAML file does not implies that all the already existing resources in the target kubernetes namespace are deleted

### What happened instead?

The folder provider as --filename parameter to the deploy command included a malformed yaml file. When the commad was executed all the existing resources in the target kubernetes namespace were deleted.

_Environment_: Azure DevOps pipelines, with bash script 

_Executed command_:
`mlp deploy --ensure-namespace=false --server $KUBE_URL --certificate-authority /tmp/kube-ca.pem --token $KUBE_TOKEN --deploy-type ${DEPLOY_TYPE} --force-deploy-when-no-semver=${FORCE_DEPLOY_WHEN_NO_SEMVER} -f ${DESTINATION_PATH} -n ${KUBE_NAMESPACE}`

_Obtained log_:
```
accumulating resources: accumulation err='accumulating resources from '../../configuration': '/home/vsts/work/1/s/configuration' must resolve to a file': recursed accumulation of path '/home/vsts/work/1/s/configuration': accumulating resources: accumulating resources from 'omitted.networkpolicy.yaml': MalformedYAMLError: yaml: line 20: could not find expected ':' in File: omitted.networkpolicy.yaml
WARN: can't read input file at path /home/vsts/work/1/s/interpolated-files/kustomize-output.yaml

Deleting: Service omitted
Deleting: Service omitted
Deleting: Service omitted
Deleting: Service omitted
Deleting: Service omitted
Deleting: Service omitted
Deleting: ConfigMap omitted
Deleting: ConfigMap omitted
Deleting: ConfigMap omitted
Deleting: ConfigMap omitted
Deleting: ConfigMap omitted
Deleting: ConfigMap omitted
Deleting: Deployment omitted
Deleting: Deployment omitted
Deleting: Deployment omitted
Deleting: Deployment omitted
Deleting: Deployment omitted
Deleting: Deployment omitted
Deleting: IngressRoute omitted
Deleting: Secret omitted
Deleting: Secret omitted
Deleting: Secret omitted
```

_file_ (before interpolation):
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: gateway-networkpolicy-ingress
spec:
  podSelector:
    matchLabels:
      app: api-gateway
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              project: {{OMITTED_NAMESPACE}}
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8081
  policyTypes:
    - Ingress
```

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct
